services:
  app:
    build:
      context: ./ 
      dockerfile: Dockerfile
    image: glow
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./:/opt/app-root/src 
    ports:
      - 3000:3000
    container_name: glow 
    
  db:
    image: docker.io/postgres:15.2-alpine
    environment:
      - PGDATA=/data 
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data 
    container_name: glow_db

volumes:
  pg_data:
